In [5]:
import pandas as pd
import numpy as np

In [6]:
data=pd.read_csv(r'C:\Users\PREETHA\Downloads\Transactionss.csv')

In [7]:
data

A  B   C  D  E
0  0  0  18  0  1
1  0  6   0  1  1
2  0  6   0  1  1
3  2  0   4  0  2
4  2  3   1  1  1
5  0  0   4  0  3

In [8]:
duplicate=data[data.duplicated()]
print(duplicate)
data.drop_duplicates()

   A  B  C  D  E
2  0  6  0  1  1


A  B   C  D  E
0  0  0  18  0  1
1  0  6   0  1  1
3  2  0   4  0  2
4  2  3   1  1  1
5  0  0   4  0  3

In [9]:
data.shape

(6, 5)

In [10]:
duplicate.shape

(1, 5)

In [11]:
data1=pd.read_csv(r'C:\Users\PREETHA\Downloads\profit table.csv')

In [12]:
data1

A   B  C  D  E
0  2  11  4  7  5

In [13]:
data1.shape

(1, 5)

In [14]:
records=[]
for i in range(0,6):
    records.append([int(data.values[i,j])for j in range(0,5)])

In [15]:
U=[]
for i in range(0,5):
    U=data.sum(axis=0)*data1.sum(axis=0)
    print(U[i])

8
165
108
21
45


In [16]:
array=data.to_numpy()
print(array)

[[ 0  0 18  0  1]
 [ 0  6  0  1  1]
 [ 0  6  0  1  1]
 [ 2  0  4  0  2]
 [ 2  3  1  1  1]
 [ 0  0  4  0  3]]


In [17]:
for i in range(0,6):
    print(array[i])

[ 0  0 18  0  1]
[0 6 0 1 1]
[0 6 0 1 1]
[2 0 4 0 2]
[2 3 1 1 1]
[0 0 4 0 3]


In [18]:
array1=data1.to_numpy()
print(array1)

[[ 2 11  4  7  5]]


In [19]:
for i in range(0,6):
    print(array[i])

[ 0  0 18  0  1]
[0 6 0 1 1]
[0 6 0 1 1]
[2 0 4 0 2]
[2 3 1 1 1]
[0 0 4 0 3]


In [20]:
array1=data1.to_numpy()
print(array1)

[[ 2 11  4  7  5]]


In [21]:
print(array1[0])

[ 2 11  4  7  5]


In [22]:
for i in range(0,5):
    if((array[0][i]!=0)):
        print((array[0])[i])

18
1


In [23]:
for i in range(0,6):
    for j in range(0,5):
        if((array[i][j]!=0)):
            print((array[i][j]))

18
1
6
1
1
6
1
1
2
4
2
2
3
1
1
1
4
3


In [24]:
str=[]
for i in range(0,6):
    for j in range(0,5):
        if(array[i][j]!=0):
            str=data.columns[j]
            print(str)

C
E
B
D
E
B
D
E
A
C
E
A
B
C
D
E
C
E


In [25]:
import itertools
for i in range(0,6):
    str=[]
#for i in range(0,6):
    for j in range(0,5):
        if(array[i][j]!=0):
            str.append(data.columns[j])
    print(str)
    all_combinations=[]
    for i in range(len(str)+1):
        combinations_object=itertools.combinations(str,i)
        combinations_list=list(combinations_object)
        all_combinations+=combinations_list
    print (all_combinations)
    

['C', 'E']
[(), ('C',), ('E',), ('C', 'E')]
['B', 'D', 'E']
[(), ('B',), ('D',), ('E',), ('B', 'D'), ('B', 'E'), ('D', 'E'), ('B', 'D', 'E')]
['B', 'D', 'E']
[(), ('B',), ('D',), ('E',), ('B', 'D'), ('B', 'E'), ('D', 'E'), ('B', 'D', 'E')]
['A', 'C', 'E']
[(), ('A',), ('C',), ('E',), ('A', 'C'), ('A', 'E'), ('C', 'E'), ('A', 'C', 'E')]
['A', 'B', 'C', 'D', 'E']
[(), ('A',), ('B',), ('C',), ('D',), ('E',), ('A', 'B'), ('A', 'C'), ('A', 'D'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'D'), ('C', 'E'), ('D', 'E'), ('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'B', 'E'), ('A', 'C', 'D'), ('A', 'C', 'E'), ('A', 'D', 'E'), ('B', 'C', 'D'), ('B', 'C', 'E'), ('B', 'D', 'E'), ('C', 'D', 'E'), ('A', 'B', 'C', 'D'), ('A', 'B', 'C', 'E'), ('A', 'B', 'D', 'E'), ('A', 'C', 'D', 'E'), ('B', 'C', 'D', 'E'), ('A', 'B', 'C', 'D', 'E')]
['C', 'E']
[(), ('C',), ('E',), ('C', 'E')]


In [29]:
all_combinations=[]
for i in range(len(str)+1):
    combinations_object=itertools.combinations(str,i)
    combinations_list=list(combinations_object)
    all_combinations+=combinations_list
print (all_combinations)
all_combinations=data.sum(axis=0)*data1.sum(axis=0)
print(all_combinations)


[(), ('C',), ('E',), ('C', 'E')]
A      8
B    165
C    108
D     21
E     45
dtype: int64


SyntaxError: unexpected EOF while parsing (<ipython-input-32-e6ae8f27fc3d>, line 3)